<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Uganda', 'iso_alpha2' => 'UG', 'flag_emoji' => '🇺🇬', 'currency_code' => 'UGX', 'currency_symbol' => 'Shs', 'default_vat_rate' => 18.00, 'region' => 'East Africa', 'calling_code' => '+256'],
            ['name' => 'Kenya', 'iso_alpha2' => 'KE', 'flag_emoji' => '🇰🇪', 'currency_code' => 'KES', 'currency_symbol' => 'KSh', 'default_vat_rate' => 16.00, 'region' => 'East Africa', 'calling_code' => '+254'],
            ['name' => 'Tanzania', 'iso_alpha2' => 'TZ', 'flag_emoji' => '🇹🇿', 'currency_code' => 'TZS', 'currency_symbol' => 'TSh', 'default_vat_rate' => 18.00, 'region' => 'East Africa', 'calling_code' => '+255'],
            ['name' => 'Rwanda', 'iso_alpha2' => 'RW', 'flag_emoji' => '🇷🇼', 'currency_code' => 'RWF', 'currency_symbol' => 'FRw', 'default_vat_rate' => 18.00, 'region' => 'East Africa', 'calling_code' => '+250'],
            ['name' => 'Burundi', 'iso_alpha2' => 'BI', 'flag_emoji' => '🇧🇮', 'currency_code' => 'BIF', 'currency_symbol' => 'FBu', 'default_vat_rate' => 18.00, 'region' => 'East Africa', 'calling_code' => '+257'],
            ['name' => 'South Sudan', 'iso_alpha2' => 'SS', 'flag_emoji' => '🇸🇸', 'currency_code' => 'SSP', 'currency_symbol' => '£', 'default_vat_rate' => 0.00, 'region' => 'East Africa', 'calling_code' => '+211'],
            ['name' => 'Ethiopia', 'iso_alpha2' => 'ET', 'flag_emoji' => '🇪🇹', 'currency_code' => 'ETB', 'currency_symbol' => 'Br', 'default_vat_rate' => 15.00, 'region' => 'East Africa', 'calling_code' => '+251'],
            ['name' => 'Somalia', 'iso_alpha2' => 'SO', 'flag_emoji' => '🇸🇴', 'currency_code' => 'SOS', 'currency_symbol' => 'Sh', 'default_vat_rate' => 0.00, 'region' => 'East Africa', 'calling_code' => '+252'],
            ['name' => 'Djibouti', 'iso_alpha2' => 'DJ', 'flag_emoji' => '🇩🇯', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj', 'default_vat_rate' => 0.00, 'region' => 'East Africa', 'calling_code' => '+253'],
            ['name' => 'Eritrea', 'iso_alpha2' => 'ER', 'flag_emoji' => '🇪🇷', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk', 'default_vat_rate' => 0.00, 'region' => 'East Africa', 'calling_code' => '+291'],
            ['name' => 'Nigeria', 'iso_alpha2' => 'NG', 'flag_emoji' => '🇳🇬', 'currency_code' => 'NGN', 'currency_symbol' => '₦', 'default_vat_rate' => 7.50, 'region' => 'West Africa', 'calling_code' => '+234'],
            ['name' => 'Ghana', 'iso_alpha2' => 'GH', 'flag_emoji' => '🇬🇭', 'currency_code' => 'GHS', 'currency_symbol' => '₵', 'default_vat_rate' => 12.50, 'region' => 'West Africa', 'calling_code' => '+233'],
            ['name' => 'South Africa', 'iso_alpha2' => 'ZA', 'flag_emoji' => '🇿🇦', 'currency_code' => 'ZAR', 'currency_symbol' => 'R', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+27'],
            ['name' => 'United States', 'iso_alpha2' => 'US', 'flag_emoji' => '🇺🇸', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'North America', 'calling_code' => '+1'],
            ['name' => 'United Kingdom', 'iso_alpha2' => 'GB', 'flag_emoji' => '🇬🇧', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+44'],
            ['name' => 'Canada', 'iso_alpha2' => 'CA', 'flag_emoji' => '🇨🇦', 'currency_code' => 'CAD', 'currency_symbol' => '$', 'default_vat_rate' => 5.00, 'region' => 'North America', 'calling_code' => '+1'],
            ['name' => 'Australia', 'iso_alpha2' => 'AU', 'flag_emoji' => '🇦🇺', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'default_vat_rate' => 10.00, 'region' => 'Oceania', 'calling_code' => '+61'],
            ['name' => 'Germany', 'iso_alpha2' => 'DE', 'flag_emoji' => '🇩🇪', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 19.00, 'region' => 'Europe', 'calling_code' => '+49'],
            ['name' => 'France', 'iso_alpha2' => 'FR', 'flag_emoji' => '🇫🇷', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+33'],
            ['name' => 'China', 'iso_alpha2' => 'CN', 'flag_emoji' => '🇨🇳', 'currency_code' => 'CNY', 'currency_symbol' => '¥', 'default_vat_rate' => 13.00, 'region' => 'East Asia', 'calling_code' => '+86'],
            ['name' => 'India', 'iso_alpha2' => 'IN', 'flag_emoji' => '🇮🇳', 'currency_code' => 'INR', 'currency_symbol' => '₹', 'default_vat_rate' => 18.00, 'region' => 'South Asia', 'calling_code' => '+91'],
            ['name' => 'Japan', 'iso_alpha2' => 'JP', 'flag_emoji' => '🇯🇵', 'currency_code' => 'JPY', 'currency_symbol' => '¥', 'default_vat_rate' => 10.00, 'region' => 'East Asia', 'calling_code' => '+81'],
            ['name' => 'United Arab Emirates', 'iso_alpha2' => 'AE', 'flag_emoji' => '🇦🇪', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ', 'default_vat_rate' => 5.00, 'region' => 'Middle East', 'calling_code' => '+971'],
            ['name' => 'Saudi Arabia', 'iso_alpha2' => 'SA', 'flag_emoji' => '🇸🇦', 'currency_code' => 'SAR', 'currency_symbol' => '﷼', 'default_vat_rate' => 15.00, 'region' => 'Middle East', 'calling_code' => '+966'],
            ['name' => 'Egypt', 'iso_alpha2' => 'EG', 'flag_emoji' => '🇪🇬', 'currency_code' => 'EGP', 'currency_symbol' => '£', 'default_vat_rate' => 14.00, 'region' => 'North Africa', 'calling_code' => '+20'],
            ['name' => 'Morocco', 'iso_alpha2' => 'MA', 'flag_emoji' => '🇲🇦', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م.', 'default_vat_rate' => 20.00, 'region' => 'North Africa', 'calling_code' => '+212'],
            ['name' => 'Algeria', 'iso_alpha2' => 'DZ', 'flag_emoji' => '🇩🇿', 'currency_code' => 'DZD', 'currency_symbol' => 'د.ج', 'default_vat_rate' => 19.00, 'region' => 'North Africa', 'calling_code' => '+213'],
            ['name' => 'Tunisia', 'iso_alpha2' => 'TN', 'flag_emoji' => '🇹🇳', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت', 'default_vat_rate' => 19.00, 'region' => 'North Africa', 'calling_code' => '+216'],
            ['name' => 'Libya', 'iso_alpha2' => 'LY', 'flag_emoji' => '🇱🇾', 'currency_code' => 'LYD', 'currency_symbol' => 'ل.د', 'default_vat_rate' => 0.00, 'region' => 'North Africa', 'calling_code' => '+218'],
            ['name' => 'Sudan', 'iso_alpha2' => 'SD', 'flag_emoji' => '🇸🇩', 'currency_code' => 'SDG', 'currency_symbol' => '£', 'default_vat_rate' => 0.00, 'region' => 'North Africa', 'calling_code' => '+249'],
            ['name' => 'Angola', 'iso_alpha2' => 'AO', 'flag_emoji' => '🇦🇴', 'currency_code' => 'AOA', 'currency_symbol' => 'Kz', 'default_vat_rate' => 14.00, 'region' => 'Central Africa', 'calling_code' => '+244'],
            ['name' => 'Cameroon', 'iso_alpha2' => 'CM', 'flag_emoji' => '🇨🇲', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'default_vat_rate' => 19.25, 'region' => 'Central Africa', 'calling_code' => '+237'],
            ['name' => 'Côte d\'Ivoire', 'iso_alpha2' => 'CI', 'flag_emoji' => '🇨🇮', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+225'],
            ['name' => 'Senegal', 'iso_alpha2' => 'SN', 'flag_emoji' => '🇸🇳', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+221'],
            ['name' => 'Mali', 'iso_alpha2' => 'ML', 'flag_emoji' => '🇲🇱', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+223'],
            ['name' => 'Burkina Faso', 'iso_alpha2' => 'BF', 'flag_emoji' => '🇧🇫', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+226'],
            ['name' => 'Niger', 'iso_alpha2' => 'NE', 'flag_emoji' => '🇳🇪', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 19.00, 'region' => 'West Africa', 'calling_code' => '+227'],
            ['name' => 'Benin', 'iso_alpha2' => 'BJ', 'flag_emoji' => '🇧🇯', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+229'],
            ['name' => 'Togo', 'iso_alpha2' => 'TG', 'flag_emoji' => '🇹🇬', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+228'],
            ['name' => 'Guinea', 'iso_alpha2' => 'GN', 'flag_emoji' => '🇬🇳', 'currency_code' => 'GNF', 'currency_symbol' => 'FG', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+224'],
            ['name' => 'Sierra Leone', 'iso_alpha2' => 'SL', 'flag_emoji' => '🇸🇱', 'currency_code' => 'SLL', 'currency_symbol' => 'Le', 'default_vat_rate' => 15.00, 'region' => 'West Africa', 'calling_code' => '+232'],
            ['name' => 'Liberia', 'iso_alpha2' => 'LR', 'flag_emoji' => '🇱🇷', 'currency_code' => 'LRD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'West Africa', 'calling_code' => '+231'],
            ['name' => 'Gambia', 'iso_alpha2' => 'GM', 'flag_emoji' => '🇬🇲', 'currency_code' => 'GMD', 'currency_symbol' => 'D', 'default_vat_rate' => 15.00, 'region' => 'West Africa', 'calling_code' => '+220'],
            ['name' => 'Guinea-Bissau', 'iso_alpha2' => 'GW', 'flag_emoji' => '🇬🇼', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'default_vat_rate' => 18.00, 'region' => 'West Africa', 'calling_code' => '+245'],
            ['name' => 'Cabo Verde', 'iso_alpha2' => 'CV', 'flag_emoji' => '🇨🇻', 'currency_code' => 'CVE', 'currency_symbol' => 'Esc', 'default_vat_rate' => 15.00, 'region' => 'West Africa', 'calling_code' => '+238'],
            ['name' => 'Mauritania', 'iso_alpha2' => 'MR', 'flag_emoji' => '🇲🇷', 'currency_code' => 'MRU', 'currency_symbol' => 'UM', 'default_vat_rate' => 16.00, 'region' => 'West Africa', 'calling_code' => '+222'],
            ['name' => 'Chad', 'iso_alpha2' => 'TD', 'flag_emoji' => '🇹🇩', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'default_vat_rate' => 18.00, 'region' => 'Central Africa', 'calling_code' => '+235'],
            ['name' => 'Central African Republic', 'iso_alpha2' => 'CF', 'flag_emoji' => '🇨🇫', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'default_vat_rate' => 19.00, 'region' => 'Central Africa', 'calling_code' => '+236'],
            ['name' => 'Congo', 'iso_alpha2' => 'CG', 'flag_emoji' => '🇨🇬', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'default_vat_rate' => 18.00, 'region' => 'Central Africa', 'calling_code' => '+242'],
            ['name' => 'Democratic Republic of the Congo', 'iso_alpha2' => 'CD', 'flag_emoji' => '🇨🇩', 'currency_code' => 'CDF', 'currency_symbol' => 'FC', 'default_vat_rate' => 16.00, 'region' => 'Central Africa', 'calling_code' => '+243'],
            ['name' => 'Gabon', 'iso_alpha2' => 'GA', 'flag_emoji' => '🇬🇦', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'default_vat_rate' => 18.00, 'region' => 'Central Africa', 'calling_code' => '+241'],
            ['name' => 'Equatorial Guinea', 'iso_alpha2' => 'GQ', 'flag_emoji' => '🇬🇶', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'default_vat_rate' => 15.00, 'region' => 'Central Africa', 'calling_code' => '+240'],
            ['name' => 'São Tomé and Príncipe', 'iso_alpha2' => 'ST', 'flag_emoji' => '🇸🇹', 'currency_code' => 'STN', 'currency_symbol' => 'Db', 'default_vat_rate' => 0.00, 'region' => 'Central Africa', 'calling_code' => '+239'],
            ['name' => 'Zambia', 'iso_alpha2' => 'ZM', 'flag_emoji' => '🇿🇲', 'currency_code' => 'ZMW', 'currency_symbol' => 'ZK', 'default_vat_rate' => 16.00, 'region' => 'Southern Africa', 'calling_code' => '+260'],
            ['name' => 'Zimbabwe', 'iso_alpha2' => 'ZW', 'flag_emoji' => '🇿🇼', 'currency_code' => 'ZWL', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+263'],
            ['name' => 'Mozambique', 'iso_alpha2' => 'MZ', 'flag_emoji' => '🇲🇿', 'currency_code' => 'MZN', 'currency_symbol' => 'MT', 'default_vat_rate' => 17.00, 'region' => 'Southern Africa', 'calling_code' => '+258'],
            ['name' => 'Malawi', 'iso_alpha2' => 'MW', 'flag_emoji' => '🇲🇼', 'currency_code' => 'MWK', 'currency_symbol' => 'MK', 'default_vat_rate' => 16.50, 'region' => 'Southern Africa', 'calling_code' => '+265'],
            ['name' => 'Botswana', 'iso_alpha2' => 'BW', 'flag_emoji' => '🇧🇼', 'currency_code' => 'BWP', 'currency_symbol' => 'P', 'default_vat_rate' => 14.00, 'region' => 'Southern Africa', 'calling_code' => '+267'],
            ['name' => 'Namibia', 'iso_alpha2' => 'NA', 'flag_emoji' => '🇳🇦', 'currency_code' => 'NAD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+264'],
            ['name' => 'Eswatini', 'iso_alpha2' => 'SZ', 'flag_emoji' => '🇸🇿', 'currency_code' => 'SZL', 'currency_symbol' => 'E', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+268'],
            ['name' => 'Lesotho', 'iso_alpha2' => 'LS', 'flag_emoji' => '🇱🇸', 'currency_code' => 'LSL', 'currency_symbol' => 'L', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+266'],
            ['name' => 'Mauritius', 'iso_alpha2' => 'MU', 'flag_emoji' => '🇲🇺', 'currency_code' => 'MUR', 'currency_symbol' => '₨', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+230'],
            ['name' => 'Madagascar', 'iso_alpha2' => 'MG', 'flag_emoji' => '🇲🇬', 'currency_code' => 'MGA', 'currency_symbol' => 'Ar', 'default_vat_rate' => 20.00, 'region' => 'Southern Africa', 'calling_code' => '+261'],
            ['name' => 'Seychelles', 'iso_alpha2' => 'SC', 'flag_emoji' => '🇸🇨', 'currency_code' => 'SCR', 'currency_symbol' => '₨', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+248'],
            ['name' => 'Comoros', 'iso_alpha2' => 'KM', 'flag_emoji' => '🇰🇲', 'currency_code' => 'KMF', 'currency_symbol' => 'CF', 'default_vat_rate' => 0.00, 'region' => 'Southern Africa', 'calling_code' => '+269'],
            ['name' => 'Netherlands', 'iso_alpha2' => 'NL', 'flag_emoji' => '🇳🇱', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+31'],
            ['name' => 'Belgium', 'iso_alpha2' => 'BE', 'flag_emoji' => '🇧🇪', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+32'],
            ['name' => 'Switzerland', 'iso_alpha2' => 'CH', 'flag_emoji' => '🇨🇭', 'currency_code' => 'CHF', 'currency_symbol' => 'Fr', 'default_vat_rate' => 8.10, 'region' => 'Europe', 'calling_code' => '+41'],
            ['name' => 'Austria', 'iso_alpha2' => 'AT', 'flag_emoji' => '🇦🇹', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+43'],
            ['name' => 'Italy', 'iso_alpha2' => 'IT', 'flag_emoji' => '🇮🇹', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 22.00, 'region' => 'Europe', 'calling_code' => '+39'],
            ['name' => 'Spain', 'iso_alpha2' => 'ES', 'flag_emoji' => '🇪🇸', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+34'],
            ['name' => 'Portugal', 'iso_alpha2' => 'PT', 'flag_emoji' => '🇵🇹', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 23.00, 'region' => 'Europe', 'calling_code' => '+351'],
            ['name' => 'Sweden', 'iso_alpha2' => 'SE', 'flag_emoji' => '🇸🇪', 'currency_code' => 'SEK', 'currency_symbol' => 'kr', 'default_vat_rate' => 25.00, 'region' => 'Europe', 'calling_code' => '+46'],
            ['name' => 'Norway', 'iso_alpha2' => 'NO', 'flag_emoji' => '🇳🇴', 'currency_code' => 'NOK', 'currency_symbol' => 'kr', 'default_vat_rate' => 25.00, 'region' => 'Europe', 'calling_code' => '+47'],
            ['name' => 'Denmark', 'iso_alpha2' => 'DK', 'flag_emoji' => '🇩🇰', 'currency_code' => 'DKK', 'currency_symbol' => 'kr', 'default_vat_rate' => 25.00, 'region' => 'Europe', 'calling_code' => '+45'],
            ['name' => 'Finland', 'iso_alpha2' => 'FI', 'flag_emoji' => '🇫🇮', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 25.50, 'region' => 'Europe', 'calling_code' => '+358'],
            ['name' => 'Poland', 'iso_alpha2' => 'PL', 'flag_emoji' => '🇵🇱', 'currency_code' => 'PLN', 'currency_symbol' => 'zł', 'default_vat_rate' => 23.00, 'region' => 'Europe', 'calling_code' => '+48'],
            ['name' => 'Czech Republic', 'iso_alpha2' => 'CZ', 'flag_emoji' => '🇨🇿', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+420'],
            ['name' => 'Slovakia', 'iso_alpha2' => 'SK', 'flag_emoji' => '🇸🇰', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 23.00, 'region' => 'Europe', 'calling_code' => '+421'],
            ['name' => 'Hungary', 'iso_alpha2' => 'HU', 'flag_emoji' => '🇭🇺', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft', 'default_vat_rate' => 27.00, 'region' => 'Europe', 'calling_code' => '+36'],
            ['name' => 'Romania', 'iso_alpha2' => 'RO', 'flag_emoji' => '🇷🇴', 'currency_code' => 'RON', 'currency_symbol' => 'lei', 'default_vat_rate' => 19.00, 'region' => 'Europe', 'calling_code' => '+40'],
            ['name' => 'Bulgaria', 'iso_alpha2' => 'BG', 'flag_emoji' => '🇧🇬', 'currency_code' => 'BGN', 'currency_symbol' => 'лв', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+359'],
            ['name' => 'Greece', 'iso_alpha2' => 'GR', 'flag_emoji' => '🇬🇷', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 24.00, 'region' => 'Europe', 'calling_code' => '+30'],
            ['name' => 'Ireland', 'iso_alpha2' => 'IE', 'flag_emoji' => '🇮🇪', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 23.00, 'region' => 'Europe', 'calling_code' => '+353'],
            ['name' => 'Russia', 'iso_alpha2' => 'RU', 'flag_emoji' => '🇷🇺', 'currency_code' => 'RUB', 'currency_symbol' => '₽', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+7'],
            ['name' => 'Ukraine', 'iso_alpha2' => 'UA', 'flag_emoji' => '🇺🇦', 'currency_code' => 'UAH', 'currency_symbol' => '₴', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+380'],
            ['name' => 'Turkey', 'iso_alpha2' => 'TR', 'flag_emoji' => '🇹🇷', 'currency_code' => 'TRY', 'currency_symbol' => '₺', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+90'],
            ['name' => 'Israel', 'iso_alpha2' => 'IL', 'flag_emoji' => '🇮🇱', 'currency_code' => 'ILS', 'currency_symbol' => '₪', 'default_vat_rate' => 17.00, 'region' => 'Middle East', 'calling_code' => '+972'],
            ['name' => 'Qatar', 'iso_alpha2' => 'QA', 'flag_emoji' => '🇶🇦', 'currency_code' => 'QAR', 'currency_symbol' => '﷼', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+974'],
            ['name' => 'Kuwait', 'iso_alpha2' => 'KW', 'flag_emoji' => '🇰🇼', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+965'],
            ['name' => 'Bahrain', 'iso_alpha2' => 'BH', 'flag_emoji' => '🇧🇭', 'currency_code' => 'BHD', 'currency_symbol' => '.د.ب', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+973'],
            ['name' => 'Oman', 'iso_alpha2' => 'OM', 'flag_emoji' => '🇴🇲', 'currency_code' => 'OMR', 'currency_symbol' => '﷼', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+968'],
            ['name' => 'Yemen', 'iso_alpha2' => 'YE', 'flag_emoji' => '🇾🇪', 'currency_code' => 'YER', 'currency_symbol' => '﷼', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+967'],
            ['name' => 'Syria', 'iso_alpha2' => 'SY', 'flag_emoji' => '🇸🇾', 'currency_code' => 'SYP', 'currency_symbol' => '£', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+963'],
            ['name' => 'Jordan', 'iso_alpha2' => 'JO', 'flag_emoji' => '🇯🇴', 'currency_code' => 'JOD', 'currency_symbol' => 'د.ا', 'default_vat_rate' => 16.00, 'region' => 'Middle East', 'calling_code' => '+962'],
            ['name' => 'Lebanon', 'iso_alpha2' => 'LB', 'flag_emoji' => '🇱🇧', 'currency_code' => 'LBP', 'currency_symbol' => 'ل.ل', 'default_vat_rate' => 11.00, 'region' => 'Middle East', 'calling_code' => '+961'],
            ['name' => 'Iraq', 'iso_alpha2' => 'IQ', 'flag_emoji' => '🇮🇶', 'currency_code' => 'IQD', 'currency_symbol' => 'ع.د', 'default_vat_rate' => 0.00, 'region' => 'Middle East', 'calling_code' => '+964'],
            ['name' => 'Iran', 'iso_alpha2' => 'IR', 'flag_emoji' => '🇮🇷', 'currency_code' => 'IRR', 'currency_symbol' => '﷼', 'default_vat_rate' => 9.00, 'region' => 'Middle East', 'calling_code' => '+98'],
            ['name' => 'Afghanistan', 'iso_alpha2' => 'AF', 'flag_emoji' => '🇦🇫', 'currency_code' => 'AFN', 'currency_symbol' => '؋', 'default_vat_rate' => 0.00, 'region' => 'South Asia', 'calling_code' => '+93'],
            ['name' => 'Pakistan', 'iso_alpha2' => 'PK', 'flag_emoji' => '🇵🇰', 'currency_code' => 'PKR', 'currency_symbol' => '₨', 'default_vat_rate' => 17.00, 'region' => 'South Asia', 'calling_code' => '+92'],
            ['name' => 'Bangladesh', 'iso_alpha2' => 'BD', 'flag_emoji' => '🇧🇩', 'currency_code' => 'BDT', 'currency_symbol' => '৳', 'default_vat_rate' => 15.00, 'region' => 'South Asia', 'calling_code' => '+880'],
            ['name' => 'Sri Lanka', 'iso_alpha2' => 'LK', 'flag_emoji' => '🇱🇰', 'currency_code' => 'LKR', 'currency_symbol' => '₨', 'default_vat_rate' => 15.00, 'region' => 'South Asia', 'calling_code' => '+94'],
            ['name' => 'Nepal', 'iso_alpha2' => 'NP', 'flag_emoji' => '🇳🇵', 'currency_code' => 'NPR', 'currency_symbol' => '₨', 'default_vat_rate' => 13.00, 'region' => 'South Asia', 'calling_code' => '+977'],
            ['name' => 'Bhutan', 'iso_alpha2' => 'BT', 'flag_emoji' => '🇧🇹', 'currency_code' => 'BTN', 'currency_symbol' => 'Nu', 'default_vat_rate' => 0.00, 'region' => 'South Asia', 'calling_code' => '+975'],
            ['name' => 'Maldives', 'iso_alpha2' => 'MV', 'flag_emoji' => '🇲🇻', 'currency_code' => 'MVR', 'currency_symbol' => 'Rf', 'default_vat_rate' => 8.00, 'region' => 'South Asia', 'calling_code' => '+960'],
            ['name' => 'Myanmar', 'iso_alpha2' => 'MM', 'flag_emoji' => '🇲🇲', 'currency_code' => 'MMK', 'currency_symbol' => 'K', 'default_vat_rate' => 0.00, 'region' => 'Southeast Asia', 'calling_code' => '+95'],
            ['name' => 'Thailand', 'iso_alpha2' => 'TH', 'flag_emoji' => '🇹🇭', 'currency_code' => 'THB', 'currency_symbol' => '฿', 'default_vat_rate' => 7.00, 'region' => 'Southeast Asia', 'calling_code' => '+66'],
            ['name' => 'Vietnam', 'iso_alpha2' => 'VN', 'flag_emoji' => '🇻🇳', 'currency_code' => 'VND', 'currency_symbol' => '₫', 'default_vat_rate' => 10.00, 'region' => 'Southeast Asia', 'calling_code' => '+84'],
            ['name' => 'Cambodia', 'iso_alpha2' => 'KH', 'flag_emoji' => '🇰🇭', 'currency_code' => 'KHR', 'currency_symbol' => '៛', 'default_vat_rate' => 10.00, 'region' => 'Southeast Asia', 'calling_code' => '+855'],
            ['name' => 'Laos', 'iso_alpha2' => 'LA', 'flag_emoji' => '🇱🇦', 'currency_code' => 'LAK', 'currency_symbol' => '₭', 'default_vat_rate' => 10.00, 'region' => 'Southeast Asia', 'calling_code' => '+856'],
            ['name' => 'Malaysia', 'iso_alpha2' => 'MY', 'flag_emoji' => '🇲🇾', 'currency_code' => 'MYR', 'currency_symbol' => 'RM', 'default_vat_rate' => 10.00, 'region' => 'Southeast Asia', 'calling_code' => '+60'],
            ['name' => 'Singapore', 'iso_alpha2' => 'SG', 'flag_emoji' => '🇸🇬', 'currency_code' => 'SGD', 'currency_symbol' => '$', 'default_vat_rate' => 9.00, 'region' => 'Southeast Asia', 'calling_code' => '+65'],
            ['name' => 'Indonesia', 'iso_alpha2' => 'ID', 'flag_emoji' => '🇮🇩', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp', 'default_vat_rate' => 11.00, 'region' => 'Southeast Asia', 'calling_code' => '+62'],
            ['name' => 'Philippines', 'iso_alpha2' => 'PH', 'flag_emoji' => '🇵🇭', 'currency_code' => 'PHP', 'currency_symbol' => '₱', 'default_vat_rate' => 12.00, 'region' => 'Southeast Asia', 'calling_code' => '+63'],
            ['name' => 'Brunei', 'iso_alpha2' => 'BN', 'flag_emoji' => '🇧🇳', 'currency_code' => 'BND', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Southeast Asia', 'calling_code' => '+673'],
            ['name' => 'Timor-Leste', 'iso_alpha2' => 'TL', 'flag_emoji' => '🇹🇱', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Southeast Asia', 'calling_code' => '+670'],
            ['name' => 'South Korea', 'iso_alpha2' => 'KR', 'flag_emoji' => '🇰🇷', 'currency_code' => 'KRW', 'currency_symbol' => '₩', 'default_vat_rate' => 10.00, 'region' => 'East Asia', 'calling_code' => '+82'],
            ['name' => 'North Korea', 'iso_alpha2' => 'KP', 'flag_emoji' => '🇰🇵', 'currency_code' => 'KPW', 'currency_symbol' => '₩', 'default_vat_rate' => 0.00, 'region' => 'East Asia', 'calling_code' => '+850'],
            ['name' => 'Mongolia', 'iso_alpha2' => 'MN', 'flag_emoji' => '🇲🇳', 'currency_code' => 'MNT', 'currency_symbol' => '₮', 'default_vat_rate' => 10.00, 'region' => 'East Asia', 'calling_code' => '+976'],
            ['name' => 'Taiwan', 'iso_alpha2' => 'TW', 'flag_emoji' => '🇹🇼', 'currency_code' => 'TWD', 'currency_symbol' => 'NT$', 'default_vat_rate' => 5.00, 'region' => 'East Asia', 'calling_code' => '+886'],
            ['name' => 'Hong Kong', 'iso_alpha2' => 'HK', 'flag_emoji' => '🇭🇰', 'currency_code' => 'HKD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'East Asia', 'calling_code' => '+852'],
            ['name' => 'Macau', 'iso_alpha2' => 'MO', 'flag_emoji' => '🇲🇴', 'currency_code' => 'MOP', 'currency_symbol' => 'P', 'default_vat_rate' => 0.00, 'region' => 'East Asia', 'calling_code' => '+853'],
            ['name' => 'Argentina', 'iso_alpha2' => 'AR', 'flag_emoji' => '🇦🇷', 'currency_code' => 'ARS', 'currency_symbol' => '$', 'default_vat_rate' => 21.00, 'region' => 'South America', 'calling_code' => '+54'],
            ['name' => 'Bolivia', 'iso_alpha2' => 'BO', 'flag_emoji' => '🇧🇴', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs', 'default_vat_rate' => 13.00, 'region' => 'South America', 'calling_code' => '+591'],
            ['name' => 'Brazil', 'iso_alpha2' => 'BR', 'flag_emoji' => '🇧🇷', 'currency_code' => 'BRL', 'currency_symbol' => 'R$', 'default_vat_rate' => 17.00, 'region' => 'South America', 'calling_code' => '+55'],
            ['name' => 'Chile', 'iso_alpha2' => 'CL', 'flag_emoji' => '🇨🇱', 'currency_code' => 'CLP', 'currency_symbol' => '$', 'default_vat_rate' => 19.00, 'region' => 'South America', 'calling_code' => '+56'],
            ['name' => 'Colombia', 'iso_alpha2' => 'CO', 'flag_emoji' => '🇨🇴', 'currency_code' => 'COP', 'currency_symbol' => '$', 'default_vat_rate' => 19.00, 'region' => 'South America', 'calling_code' => '+57'],
            ['name' => 'Ecuador', 'iso_alpha2' => 'EC', 'flag_emoji' => '🇪🇨', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 12.00, 'region' => 'South America', 'calling_code' => '+593'],
            ['name' => 'Guyana', 'iso_alpha2' => 'GY', 'flag_emoji' => '🇬🇾', 'currency_code' => 'GYD', 'currency_symbol' => '$', 'default_vat_rate' => 14.00, 'region' => 'South America', 'calling_code' => '+592'],
            ['name' => 'Paraguay', 'iso_alpha2' => 'PY', 'flag_emoji' => '🇵🇾', 'currency_code' => 'PYG', 'currency_symbol' => '₲', 'default_vat_rate' => 10.00, 'region' => 'South America', 'calling_code' => '+595'],
            ['name' => 'Peru', 'iso_alpha2' => 'PE', 'flag_emoji' => '🇵🇪', 'currency_code' => 'PEN', 'currency_symbol' => 'S/', 'default_vat_rate' => 18.00, 'region' => 'South America', 'calling_code' => '+51'],
            ['name' => 'Suriname', 'iso_alpha2' => 'SR', 'flag_emoji' => '🇸🇷', 'currency_code' => 'SRD', 'currency_symbol' => '$', 'default_vat_rate' => 10.00, 'region' => 'South America', 'calling_code' => '+597'],
            ['name' => 'Uruguay', 'iso_alpha2' => 'UY', 'flag_emoji' => '🇺🇾', 'currency_code' => 'UYU', 'currency_symbol' => '$', 'default_vat_rate' => 22.00, 'region' => 'South America', 'calling_code' => '+598'],
            ['name' => 'Venezuela', 'iso_alpha2' => 'VE', 'flag_emoji' => '🇻🇪', 'currency_code' => 'VES', 'currency_symbol' => 'Bs', 'default_vat_rate' => 16.00, 'region' => 'South America', 'calling_code' => '+58'],
            ['name' => 'Mexico', 'iso_alpha2' => 'MX', 'flag_emoji' => '🇲🇽', 'currency_code' => 'MXN', 'currency_symbol' => '$', 'default_vat_rate' => 16.00, 'region' => 'North America', 'calling_code' => '+52'],
            ['name' => 'Cuba', 'iso_alpha2' => 'CU', 'flag_emoji' => '🇨🇺', 'currency_code' => 'CUP', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Caribbean', 'calling_code' => '+53'],
            ['name' => 'Jamaica', 'iso_alpha2' => 'JM', 'flag_emoji' => '🇯🇲', 'currency_code' => 'JMD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Caribbean', 'calling_code' => '+1-876'],
            ['name' => 'Haiti', 'iso_alpha2' => 'HT', 'flag_emoji' => '🇭🇹', 'currency_code' => 'HTG', 'currency_symbol' => 'G', 'default_vat_rate' => 10.00, 'region' => 'Caribbean', 'calling_code' => '+509'],
            ['name' => 'Dominican Republic', 'iso_alpha2' => 'DO', 'flag_emoji' => '🇩🇴', 'currency_code' => 'DOP', 'currency_symbol' => 'RD$', 'default_vat_rate' => 18.00, 'region' => 'Caribbean', 'calling_code' => '+1-809'],
            ['name' => 'Bahamas', 'iso_alpha2' => 'BS', 'flag_emoji' => '🇧🇸', 'currency_code' => 'BSD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Caribbean', 'calling_code' => '+1-242'],
            ['name' => 'Barbados', 'iso_alpha2' => 'BB', 'flag_emoji' => '🇧🇧', 'currency_code' => 'BBD', 'currency_symbol' => '$', 'default_vat_rate' => 17.50, 'region' => 'Caribbean', 'calling_code' => '+1-246'],
            ['name' => 'Trinidad and Tobago', 'iso_alpha2' => 'TT', 'flag_emoji' => '🇹🇹', 'currency_code' => 'TTD', 'currency_symbol' => 'TT$', 'default_vat_rate' => 12.50, 'region' => 'Caribbean', 'calling_code' => '+1-868'],
            ['name' => 'Costa Rica', 'iso_alpha2' => 'CR', 'flag_emoji' => '🇨🇷', 'currency_code' => 'CRC', 'currency_symbol' => '₡', 'default_vat_rate' => 13.00, 'region' => 'Central America', 'calling_code' => '+506'],
            ['name' => 'El Salvador', 'iso_alpha2' => 'SV', 'flag_emoji' => '🇸🇻', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 13.00, 'region' => 'Central America', 'calling_code' => '+503'],
            ['name' => 'Guatemala', 'iso_alpha2' => 'GT', 'flag_emoji' => '🇬🇹', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q', 'default_vat_rate' => 12.00, 'region' => 'Central America', 'calling_code' => '+502'],
            ['name' => 'Honduras', 'iso_alpha2' => 'HN', 'flag_emoji' => '🇭🇳', 'currency_code' => 'HNL', 'currency_symbol' => 'L', 'default_vat_rate' => 15.00, 'region' => 'Central America', 'calling_code' => '+504'],
            ['name' => 'Nicaragua', 'iso_alpha2' => 'NI', 'flag_emoji' => '🇳🇮', 'currency_code' => 'NIO', 'currency_symbol' => 'C$', 'default_vat_rate' => 15.00, 'region' => 'Central America', 'calling_code' => '+505'],
            ['name' => 'Panama', 'iso_alpha2' => 'PA', 'flag_emoji' => '🇵🇦', 'currency_code' => 'PAB', 'currency_symbol' => 'B/.', 'default_vat_rate' => 7.00, 'region' => 'Central America', 'calling_code' => '+507'],
            ['name' => 'Belize', 'iso_alpha2' => 'BZ', 'flag_emoji' => '🇧🇿', 'currency_code' => 'BZD', 'currency_symbol' => 'BZ$', 'default_vat_rate' => 12.50, 'region' => 'Central America', 'calling_code' => '+501'],
            ['name' => 'New Zealand', 'iso_alpha2' => 'NZ', 'flag_emoji' => '🇳🇿', 'currency_code' => 'NZD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Oceania', 'calling_code' => '+64'],
            ['name' => 'Papua New Guinea', 'iso_alpha2' => 'PG', 'flag_emoji' => '🇵🇬', 'currency_code' => 'PGK', 'currency_symbol' => 'K', 'default_vat_rate' => 10.00, 'region' => 'Oceania', 'calling_code' => '+675'],
            ['name' => 'Fiji', 'iso_alpha2' => 'FJ', 'flag_emoji' => '🇫🇯', 'currency_code' => 'FJD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Oceania', 'calling_code' => '+679'],
            ['name' => 'Solomon Islands', 'iso_alpha2' => 'SB', 'flag_emoji' => '🇸🇧', 'currency_code' => 'SBD', 'currency_symbol' => '$', 'default_vat_rate' => 10.00, 'region' => 'Oceania', 'calling_code' => '+677'],
            ['name' => 'Vanuatu', 'iso_alpha2' => 'VU', 'flag_emoji' => '🇻🇺', 'currency_code' => 'VUV', 'currency_symbol' => 'VT', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+678'],
            ['name' => 'Samoa', 'iso_alpha2' => 'WS', 'flag_emoji' => '🇼🇸', 'currency_code' => 'WST', 'currency_symbol' => 'T', 'default_vat_rate' => 15.00, 'region' => 'Oceania', 'calling_code' => '+685'],
            ['name' => 'Tonga', 'iso_alpha2' => 'TO', 'flag_emoji' => '🇹🇴', 'currency_code' => 'TOP', 'currency_symbol' => 'T$', 'default_vat_rate' => 15.00, 'region' => 'Oceania', 'calling_code' => '+676'],
            ['name' => 'Kiribati', 'iso_alpha2' => 'KI', 'flag_emoji' => '🇰🇮', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+686'],
            ['name' => 'Micronesia', 'iso_alpha2' => 'FM', 'flag_emoji' => '🇫🇲', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+691'],
            ['name' => 'Marshall Islands', 'iso_alpha2' => 'MH', 'flag_emoji' => '🇲🇭', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+692'],
            ['name' => 'Palau', 'iso_alpha2' => 'PW', 'flag_emoji' => '🇵🇼', 'currency_code' => 'USD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+680'],
            ['name' => 'Nauru', 'iso_alpha2' => 'NR', 'flag_emoji' => '🇳🇷', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+674'],
            ['name' => 'Tuvalu', 'iso_alpha2' => 'TV', 'flag_emoji' => '🇹🇻', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'default_vat_rate' => 0.00, 'region' => 'Oceania', 'calling_code' => '+688'],
            ['name' => 'Croatia', 'iso_alpha2' => 'HR', 'flag_emoji' => '🇭🇷', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 25.00, 'region' => 'Europe', 'calling_code' => '+385'],
            ['name' => 'Serbia', 'iso_alpha2' => 'RS', 'flag_emoji' => '🇷🇸', 'currency_code' => 'RSD', 'currency_symbol' => 'дин', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+381'],
            ['name' => 'Bosnia and Herzegovina', 'iso_alpha2' => 'BA', 'flag_emoji' => '🇧🇦', 'currency_code' => 'BAM', 'currency_symbol' => 'KM', 'default_vat_rate' => 17.00, 'region' => 'Europe', 'calling_code' => '+387'],
            ['name' => 'Albania', 'iso_alpha2' => 'AL', 'flag_emoji' => '🇦🇱', 'currency_code' => 'ALL', 'currency_symbol' => 'L', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+355'],
            ['name' => 'North Macedonia', 'iso_alpha2' => 'MK', 'flag_emoji' => '🇲🇰', 'currency_code' => 'MKD', 'currency_symbol' => 'ден', 'default_vat_rate' => 18.00, 'region' => 'Europe', 'calling_code' => '+389'],
            ['name' => 'Montenegro', 'iso_alpha2' => 'ME', 'flag_emoji' => '🇲🇪', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+382'],
            ['name' => 'Kosovo', 'iso_alpha2' => 'XK', 'flag_emoji' => '🇽🇰', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 18.00, 'region' => 'Europe', 'calling_code' => '+383'],
            ['name' => 'Iceland', 'iso_alpha2' => 'IS', 'flag_emoji' => '🇮🇸', 'currency_code' => 'ISK', 'currency_symbol' => 'kr', 'default_vat_rate' => 24.00, 'region' => 'Europe', 'calling_code' => '+354'],
            ['name' => 'Liechtenstein', 'iso_alpha2' => 'LI', 'flag_emoji' => '🇱🇮', 'currency_code' => 'CHF', 'currency_symbol' => 'Fr', 'default_vat_rate' => 8.10, 'region' => 'Europe', 'calling_code' => '+423'],
            ['name' => 'Luxembourg', 'iso_alpha2' => 'LU', 'flag_emoji' => '🇱🇺', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 17.00, 'region' => 'Europe', 'calling_code' => '+352'],
            ['name' => 'Malta', 'iso_alpha2' => 'MT', 'flag_emoji' => '🇲🇹', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 18.00, 'region' => 'Europe', 'calling_code' => '+356'],
            ['name' => 'Monaco', 'iso_alpha2' => 'MC', 'flag_emoji' => '🇲🇨', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+377'],
            ['name' => 'Andorra', 'iso_alpha2' => 'AD', 'flag_emoji' => '🇦🇩', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 4.50, 'region' => 'Europe', 'calling_code' => '+376'],
            ['name' => 'San Marino', 'iso_alpha2' => 'SM', 'flag_emoji' => '🇸🇲', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 17.00, 'region' => 'Europe', 'calling_code' => '+378'],
            ['name' => 'Vatican City', 'iso_alpha2' => 'VA', 'flag_emoji' => '🇻🇦', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 0.00, 'region' => 'Europe', 'calling_code' => '+379'],
            ['name' => 'Belarus', 'iso_alpha2' => 'BY', 'flag_emoji' => '🇧🇾', 'currency_code' => 'BYN', 'currency_symbol' => 'Br', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+375'],
            ['name' => 'Moldova', 'iso_alpha2' => 'MD', 'flag_emoji' => '🇲🇩', 'currency_code' => 'MDL', 'currency_symbol' => 'L', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+373'],
            ['name' => 'Lithuania', 'iso_alpha2' => 'LT', 'flag_emoji' => '🇱🇹', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+370'],
            ['name' => 'Latvia', 'iso_alpha2' => 'LV', 'flag_emoji' => '🇱🇻', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 21.00, 'region' => 'Europe', 'calling_code' => '+371'],
            ['name' => 'Estonia', 'iso_alpha2' => 'EE', 'flag_emoji' => '🇪🇪', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 22.00, 'region' => 'Europe', 'calling_code' => '+372'],
            ['name' => 'Slovenia', 'iso_alpha2' => 'SI', 'flag_emoji' => '🇸🇮', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 22.00, 'region' => 'Europe', 'calling_code' => '+386'],
            ['name' => 'Cyprus', 'iso_alpha2' => 'CY', 'flag_emoji' => '🇨🇾', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'default_vat_rate' => 19.00, 'region' => 'Europe', 'calling_code' => '+357'],
            ['name' => 'Georgia', 'iso_alpha2' => 'GE', 'flag_emoji' => '🇬🇪', 'currency_code' => 'GEL', 'currency_symbol' => '₾', 'default_vat_rate' => 18.00, 'region' => 'Europe', 'calling_code' => '+995'],
            ['name' => 'Armenia', 'iso_alpha2' => 'AM', 'flag_emoji' => '🇦🇲', 'currency_code' => 'AMD', 'currency_symbol' => '֏', 'default_vat_rate' => 20.00, 'region' => 'Europe', 'calling_code' => '+374'],
            ['name' => 'Azerbaijan', 'iso_alpha2' => 'AZ', 'flag_emoji' => '🇦🇿', 'currency_code' => 'AZN', 'currency_symbol' => '₼', 'default_vat_rate' => 18.00, 'region' => 'Europe', 'calling_code' => '+994'],
            ['name' => 'Kazakhstan', 'iso_alpha2' => 'KZ', 'flag_emoji' => '🇰🇿', 'currency_code' => 'KZT', 'currency_symbol' => '₸', 'default_vat_rate' => 12.00, 'region' => 'Central Asia', 'calling_code' => '+7'],
            ['name' => 'Uzbekistan', 'iso_alpha2' => 'UZ', 'flag_emoji' => '🇺🇿', 'currency_code' => 'UZS', 'currency_symbol' => 'лв', 'default_vat_rate' => 15.00, 'region' => 'Central Asia', 'calling_code' => '+998'],
            ['name' => 'Turkmenistan', 'iso_alpha2' => 'TM', 'flag_emoji' => '🇹🇲', 'currency_code' => 'TMT', 'currency_symbol' => 'm', 'default_vat_rate' => 15.00, 'region' => 'Central Asia', 'calling_code' => '+993'],
            ['name' => 'Kyrgyzstan', 'iso_alpha2' => 'KG', 'flag_emoji' => '🇰🇬', 'currency_code' => 'KGS', 'currency_symbol' => 'лв', 'default_vat_rate' => 12.00, 'region' => 'Central Asia', 'calling_code' => '+996'],
            ['name' => 'Tajikistan', 'iso_alpha2' => 'TJ', 'flag_emoji' => '🇹🇯', 'currency_code' => 'TJS', 'currency_symbol' => 'ЅМ', 'default_vat_rate' => 18.00, 'region' => 'Central Asia', 'calling_code' => '+992'],
            ['name' => 'Antigua and Barbuda', 'iso_alpha2' => 'AG', 'flag_emoji' => '🇦🇬', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Caribbean', 'calling_code' => '+1-268'],
            ['name' => 'St. Kitts and Nevis', 'iso_alpha2' => 'KN', 'flag_emoji' => '🇰🇳', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'default_vat_rate' => 17.00, 'region' => 'Caribbean', 'calling_code' => '+1-869'],
            ['name' => 'St. Lucia', 'iso_alpha2' => 'LC', 'flag_emoji' => '🇱🇨', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'default_vat_rate' => 12.50, 'region' => 'Caribbean', 'calling_code' => '+1-758'],
            ['name' => 'St. Vincent and the Grenadines', 'iso_alpha2' => 'VC', 'flag_emoji' => '🇻🇨', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Caribbean', 'calling_code' => '+1-784'],
            ['name' => 'Grenada', 'iso_alpha2' => 'GD', 'flag_emoji' => '🇬🇩', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Caribbean', 'calling_code' => '+1-473'],
            ['name' => 'Dominica', 'iso_alpha2' => 'DM', 'flag_emoji' => '🇩🇲', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'default_vat_rate' => 15.00, 'region' => 'Caribbean', 'calling_code' => '+1-767'],
            ['name' => 'Lesotho', 'iso_alpha2' => 'LS', 'flag_emoji' => '🇱🇸', 'currency_code' => 'LSL', 'currency_symbol' => 'L', 'default_vat_rate' => 15.00, 'region' => 'Southern Africa', 'calling_code' => '+266'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['iso_alpha2' => $country['iso_alpha2']],
                $country
            );
        }
    }
}
