FROM dunglas/frankenphp:1.2.0-php8.3-alpine

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apk add --no-cache shadow && \
    usermod -u ${USER_ID} www-data && \
    groupmod -g ${GROUP_ID} www-data

RUN install-php-extensions \
    pgsql \
    pdo_pgsql \
    redis \
    opcache \
    pcntl \
    bcmath \
    exif

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN chown www-data:www-data /usr/local/bin/

COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chown ${USER_ID}:${GROUP_ID} /usr/local/bin/docker-entrypoint.sh && \
    chmod 755 /usr/local/bin/docker-entrypoint.sh

HEALTHCHECK --interval=30s \
    --timeout=5s \
    --start-period=20s \
    --retries=3 \
    CMD wget -qO- http://127.0.0.1:8000/up || exit 1

USER www-data

WORKDIR /app

EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD [ "php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=8000", "--watch" ]
